Add TabletDriverFilters plugins
OpenTabletDriver/Plugin-Repository pull request #6
Opened 2020-12-31 02:58 UTC by X9VoiD

2021-01-07 21:43 UTC, InfinityGhost requested changes

2021-01-07 21:43 UTC, InfinityGhost commented on Repository/0.5.0.0/OpenTabletDriver/TabletDriverFilters/HawkuFilters/v0.1.0.json
> +    "Description": "Ported Hawku Filters",
`Ported hawku/TabletDriver filters` to be more precise.

2021-01-07 21:43 UTC, InfinityGhost commented on Repository/0.5.0.0/OpenTabletDriver/TabletDriverFilters/DevocubFilters/v0.1.0.json
> +    "Description": "Ported Devocub Filters",
`Ported Devocub/TabletDriver filters` to be more precise

2021-01-08 06:53 UTC, X9VoiD commented
Requested changes pushed.

2021-01-08 18:34 UTC, InfinityGhost approved these changes

2021-01-08 18:35 UTC, merged